### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1824777086",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1824777086",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
"transactionId": "734f53aa7e0b45a2895be65b31e383d9",
"accountNumber": "1824777086",
"amount": 100
}

### query transaction
GET http://localhost:8080/transaction/734f53aa7e0b45a2895be65b31e383d9
Content-Type: application/json
